name: yunphp
version: 1
handle:
  #修改路由设置
  - rewrite: if(!is_dir() && !is_file()) goto "index.php/%{QUERY_STRING}"
  #修改404页面
  - errordoc: 404 /error/404.html
  # 强制使用https访问
  #- rewrite: if (%{REQ:X-Forwarded-Proto} != "https") goto "https://%{HTTP_HOST}%{REQUEST_URI}"